image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
- x64

# http://www.appveyor.com/docs/installed-software
environment:
  QTDIR: "C:\\Qt\\5.9.1\\msvc2017_64"
  MYCONDA: "C:\\Miniconda-x64;C:\\Miniconda-x64\\Scripts;C:\\Miniconda-x64\\Library\\bin"
  MYGIT: "C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\usr\\bin;"
  MYOTHER: "C:\\Program Files\\7-Zip"
  PATH: "%QTDIR%\\bin;C:\\opt\\local_x64\\lib;%MYCONDA%;%MYGIT%;%MYOTHER%;%PATH%"
  PYTHONPATH: "C:\\Miniconda-x64;C:\\Miniconda-x64\\Lib;C:\\Miniconda-x64\\Lib\\site-packages;C:\\Miniconda-x64\\DLLs"
build:
  parallel: true

init:  
- echo "BornAgain init"
- echo %PATH%

install:
- cmd: git submodule -q update --init
  
before_build:
- echo "BornAgain before_build"
- echo %PATH%
- python -m pip install numpy
- python -m pip install pyyaml
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/redmine/attachments/download/348/local_x64.zip -O %temp%\local_x64.zip
- 7z x %temp%\local_x64.zip -oC:\opt > null

build_script:
- mkdir build
- cd build
- cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INCLUDE_PATH=C:/opt/local_x64/include -DCMAKE_LIBRARY_PATH=C:/opt/local_x64/lib ..
- cmd: cmake --build . --config Release

test_script:
- echo "BornAgain test_script"
- echo %PATH%
- echo %PYTHONPATH%
- echo %PYTHONHOME%
- ps: >-
    ctest -LE Examples --output-on-failure

    if (-not $?) { 

        type Testing/Temporary/LastTest.log

        throw "tests failed" 

    }
