image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
- x64

# http://www.appveyor.com/docs/installed-software
environment:
  QTDIR: "C:\\Qt\\5.9\\msvc2017_64"
  MYCONDA: "C:\\Miniconda3-x64;C:\\Miniconda3-x64\\Scripts;C:\\Miniconda3-x64\\Library\\bin"
  PATH: "%QTDIR%\\bin;C:\\opt\\local_x64\\lib;%MYCONDA%;%PATH%"
  PYTHONPATH: "C:\\Miniconda3-x64;C:\\Miniconda3-x64\\Lib;C:\\Miniconda3-x64\\Lib\\site-packages;C:\\Miniconda3-x64\\DLLs"
build:
  parallel: true

init:  
- echo "BornAgain init" %CD% 
- echo %PATH%

install:
- git submodule -q update --init
  
before_build:
- echo "BornAgain before_build" %CD% 
- echo %PATH%
- python -m pip install --upgrade pip
- python -m pip install numpy
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/redmine/attachments/download/348/local_x64.zip -O %temp%\local_x64.zip
- 7z x %temp%\local_x64.zip -oC:\opt > null
- mkdir C:\projects\deps
- set CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.4-win64-x64.zip"
- appveyor DownloadFile %CMAKE_URL% -FileName %temp%\cmake.zip
- 7z x %temp%\cmake.zip -oC:\projects\deps > nul
- move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
- set PATH=C:\projects\deps\cmake\bin;%PATH%
- cmake --version

build_script:
- echo "BornAgain build_script" %CD% 
- mkdir build
- cd build
- cmake --version
- cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INCLUDE_PATH=C:/opt/local_x64/include ..
- cmake --build . --config Release

test_script:
- echo "BornAgain test_script" %CD% 
- echo %PATH%
- echo %PYTHONPATH%
- echo %PYTHONHOME%
- ps: >-
    ctest -LE Fullcheck --output-on-failure

    if (-not $?) { 

        type Testing/Temporary/LastTest.log

        throw "tests failed" 

    }
